title: Nicholas Sutanto # your name (or website title) here
logo: "/images/image0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters in Data Analytics student from Seattle Pacific University. I graduated from SPU in 2021 with a Bachelor's of Science in Information Systems.
  <br><br>
  Data analytics 
  <br><br>
  Gaming, data analysis, computers and model kits are my passion. 
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-sutanto-4259a6194/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
